
# sudo dnf update -y
# sudo dnf install -y python3 python3-pip
               #pip3 install --user ansible; echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc; source ~/.bashrc
# sudo pip3 install ansible

# ansible --version

# ansible-playbook -i <public-ip/private-ip>, playbook.yml --ssh-extra-args="-o StrictHostKeyChecking=no -o ConnectTimeout=10" \
#                                                          --private-key=ansible.pem \
#                                                          --user=ec2-user


---
- name: Install Docker and Docker-Compose
  hosts: all
  become: yes
  vars:
    compose_plugin_dir: "/usr/local/lib/docker/cli-plugins"
    compose_binary_url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    user: ec2-user
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: "{{ ( ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
      vars:
        ansible_connection: local

    - name: Ensure system packages are up to date
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: yes

    - name: Make sure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present
        update_cache: yes
     
    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Reconnect to server session
      meta: reset_connection

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker CLI plugin directory
      ansible.builtin.file:
        path: "{{ compose_plugin_dir }}"
        state: directory
        mode: "0755"

    - name: Download Docker Compose plugin binary
      ansible.builtin.get_url:
        url: "{{ compose_binary_url }}"
        dest: "{{ compose_plugin_dir }}/docker-compose"
        mode: "0755"
        force: yes

    - name: Verify Docker installation
      ansible.builtin.command: docker version
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Print installed Docker Compose version
      ansible.builtin.debug:
        msg: "{{ docker_version.stdout_lines }}"

    - name: Verify Docker Compose installation
      ansible.builtin.command: docker compose version
      register: compose_version
      changed_when: false
      failed_when: compose_version.rc != 0

    - name: Print installed Docker Compose version
      ansible.builtin.debug:
        msg: "{{ compose_version.stdout_lines }}"


