FROM nginx:stable-alpine

# Remove default configs and index
RUN rm -rf /usr/share/nginx/html/index.html /etc/nginx/conf.d/default.conf /etc/nginx/nginx.conf

# Prepare directories for non-root user
RUN mkdir -p \
      /var/cache/nginx/client_temp \
      /var/cache/nginx/proxy_temp \
      /var/cache/nginx/fastcgi_temp \
      /var/cache/nginx/uwsgi_temp \
      /var/cache/nginx/scgi_temp \
      /run \
      /etc/nginx/ssl \
    && chown -R nginx:nginx \
      /var/cache/nginx \
      /var/log/nginx \
      /etc/nginx \
      /run
    && chown -R nginx:nginx /etc/nginx
       chmod 755 /etc/nginx
       chmod 644 /etc/nginx/*.conf

  #  && chmod -R 755 /etc/nginx

# Copy custom config and frontend
COPY files/expense.conf /etc/nginx/conf.d/expense.conf

COPY code/. /usr/share/nginx/html/

EXPOSE 8080

USER nginx

CMD ["nginx", "-g", "daemon off;"]























#FROM nginx
FROM nginx:stable-alpine3.20-perl
RUN rm -rf /usr/share/nginx/html/index.html
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/cache/nginx/client_temp && \
        mkdir -p /var/cache/nginx/proxy_temp && \
        mkdir -p /var/cache/nginx/fastcgi_temp && \
        mkdir -p /var/cache/nginx/uwsgi_temp && \
        mkdir -p /var/cache/nginx/scgi_temp && \
        chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /etc/nginx/ && \
        chmod -R 755 /etc/nginx/ && \
        chown -R nginx:nginx /var/log/nginx

RUN mkdir -p /etc/nginx/ssl/ && \
    chown -R nginx:nginx /etc/nginx/ssl/ && \
    chmod -R 755 /etc/nginx/ssl/

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid /run/nginx.pid
#COPY nginx.conf /etc/nginx/nginx.conf

COPY files/expense.conf /etc/nginx/conf.d/expense.conf:ro  # Custom NGINX configuration
COPY code/. /usr/share/nginx/html/                         # copies only contents from code/ to html/
USER nginx
