apiVersion: v1
kind: Secret
metadata: 
  name: my-docker-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: << base64 encoded value of .docker/config.json file contents >>

# Note:
# 1. Do docker login
# 2. Copy the contents of ".docker/config.json" file and convert into base64 format and paste the base64 content in the above secret under ".dockerconfigjson"
